apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: notes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: notes-backend:latest
        envFrom:
        - configMapRef:
            name: notes-config
        - secretRef:
            name: notes-secrets
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /api/notes
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/notes
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: notes
spec:
  selector:
    app: backend
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
